### ISSUE TITLE
Feature request: Merge environment variables defined in environment.yaml

### ISSUE THREAD

**Issue by daviskirk** [amitbeka/conda-merge#7]
The feature request for merging environment variables defined in environment.yaml files as well the dependencies.

Conda environment.yaml spec allows us to add environment variables as well.
When merging multiple environment files, these would ideally also be present in the result.

```
name: myenv
dependencies:
    - pip=23
    - python=3.10
variables:
  PIP_EDITABLE_MODE: strict
```

for example.

**Comment by amitbeka** [comment]
Hey, looks like a good idea - I'll add this soon

**Comment by amitbeka** [comment]
Added in version 0.3.0
